### ISSUE TITLE
Color configuration

### ISSUE THREAD

**Issue by gustavdalemo** [mxrg999/TimeEditArc#9]
It would be nice to be able to configure a set of colors for each course so they're more indistinguishable from each other, but the color within the same course are more alike.

E.g

Course 1 colors: (Tomato, Flamingo, Tangerine)
Course 2 colors: (Peacock, Blueberry, Lavender)
...

Maybe an idea for a solution is to let the user input an ical per course instead of a single merged one?

TimEditArc ftw!

**Comment by mxrg999** [comment]
Thank you for your valuable suggestion! Enhancing the customization options for event visuals is indeed part of our upcoming features. 

In the meantime, I've implemented improvements to the color configuration system. A practical approach you can consider is creating separate profiles for each course. This method allows for individualized color configurations for each course, offering more control over the visual distinction of your events. 

Stay tuned for more updates!!
